# -*- coding: utf-8 -*-
"""Cleaning_Code_Project.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16xBVurtReEzvKYQDoWwxCbzD8cn7eohp
"""

from google.colab import files

# Upload your file manually
uploaded = files.upload()

# FULL CLEANING PIPELINE (Colab-ready)
# - Replaces coordinate values < 9.9999999 with median per Area (fallback to overall median)
# - Fixes Agent_Rating (>5 -> median)
# - Fixes Agent_Age (<18 or >65 -> median)
# - Calculates Delivery_Time_minutes from Order_Date + Order_Time and Pickup_Time
# - Calculates Delivery_Distance_km (Haversine)
# - Safe checks, prints summary logs

import pandas as pd
import numpy as np

# -------- CONFIG --------
file_path = "/content/amazon_delivery_raw.csv"   # change path if needed
output_path = "/content/amazon_delivery_cleaned.csv"
coord_threshold = 9.9999999                 # values < this are considered invalid
# ------------------------

# STEP 1: Load
df = pd.read_csv(file_path)
df_clean = df.copy()
print("Loaded rows:", len(df_clean))

from google.colab import drive
drive.mount('/content/drive')

# STEP 2: Standardize Area column if exists (helps grouping)
if "Area" in df_clean.columns:
    df_clean["Area"] = df_clean["Area"].astype(str).str.strip().str.title()

# STEP 3: Ensure coordinate columns exist and convert to numeric (coerce errors -> NaN)
coords = ["Store_Latitude", "Store_Longitude", "Drop_Latitude", "Drop_Longitude"]
for c in coords:
    if c in df_clean.columns:
        df_clean[c] = pd.to_numeric(df_clean[c], errors="coerce")
    else:
        print(f"Warning: column '{c}' not found in dataset. Skipping coordinate handling for it.")

# STEP 4: Replace invalid small coordinate values (< threshold) with NaN and report counts
for c in coords:
    if c in df_clean.columns:
        invalid_mask = df_clean[c].lt(coord_threshold)  # x < coord_threshold (also handles NaN gracefully)
        n_invalid = int(invalid_mask.sum())
        print(f"{c}: {n_invalid} values < {coord_threshold} -> setting to NaN")
        df_clean.loc[invalid_mask, c] = np.nan

# STEP 5: Fill coordinate NaNs with median PER Area (fallback to overall median)
if "Area" in df_clean.columns:
    # compute median per area and fill
    for c in coords:
        if c in df_clean.columns:
            # transform by group - fill NaNs within group by group's median
            df_clean[c] = df_clean.groupby("Area")[c].transform(lambda g: g.fillna(g.median()))
            # after group fill, if any NaNs remain (group median was NaN), fill with overall median
            overall_med = df_clean[c].median()
            n_remaining = int(df_clean[c].isna().sum())
            if n_remaining > 0:
                df_clean[c].fillna(overall_med, inplace=True)
            print(f"{c}: filled NaNs with median per Area (overall median used for remaining = {overall_med})")
else:
    # No Area column -> fill with overall median
    for c in coords:
        if c in df_clean.columns:
            med = df_clean[c].median()
            df_clean[c].fillna(med, inplace=True)
            print(f"Area column missing. {c}: filled NaNs with overall median = {med}")

# STEP 6: Now handle other missing numeric/categorical columns (safe)
# Fill numeric NaNs with column mean (skip coordinate cols since handled)
numeric_cols = df_clean.select_dtypes(include=[np.number]).columns.tolist()
for col in numeric_cols:
    if col in coords:   # already handled
        continue
    n_missing = int(df_clean[col].isna().sum())
    if n_missing > 0:
        mean_val = df_clean[col].mean()
        df_clean[col].fillna(mean_val, inplace=True)
        print(f"{col}: filled {n_missing} NaNs with mean = {mean_val}")

# Fill categorical NaNs with mode (if any)
categorical_cols = df_clean.select_dtypes(include=['object']).columns.tolist()
for col in categorical_cols:
    n_missing = int(df_clean[col].isna().sum())
    if n_missing > 0:
        mode_series = df_clean[col].mode()
        if not mode_series.empty:
            df_clean[col].fillna(mode_series.iloc[0], inplace=True)
            print(f"{col}: filled {n_missing} NaNs with mode = '{mode_series.iloc[0]}'")
        else:
            # no mode (all NaN?) -> fill with 'Unknown'
            df_clean[col].fillna("Unknown", inplace=True)
            print(f"{col}: filled {n_missing} NaNs with 'Unknown' (no mode found)")

# STEP 7: Drop duplicate rows
before_dup = len(df_clean)
df_clean.drop_duplicates(inplace=True)
dropped = before_dup - len(df_clean)
print(f"Dropped {dropped} duplicate rows")

# STEP 8: Fix Order_Rating (>5 -> median)
if "Order_Rating" in df_clean.columns:
    median_rating = df_clean["Order_Rating"].median()
    mask_bad_rating = df_clean["Order_Rating"] > 5
    n_bad = int(mask_bad_rating.sum())
    if n_bad > 0:
        df_clean.loc[mask_bad_rating, "Order_Rating"] = median_rating
    print(f"Order_Rating: replaced {n_bad} values > 5 with median = {median_rating}")

# STEP 9: Fix Agent_Age (<18 or >65 -> median)
if "Agent_Age" in df_clean.columns:
    median_age = df_clean["Agent_Age"].median()
    mask_bad_age = (df_clean["Agent_Age"] < 18) | (df_clean["Agent_Age"] > 65)
    n_bad_age = int(mask_bad_age.sum())
    if n_bad_age > 0:
        df_clean.loc[mask_bad_age, "Agent_Age"] = median_age
    print(f"Agent_Age: replaced {n_bad_age} out-of-range values with median = {median_age}")

# STEP 10: Calculate Delivery_Time_minutes from Order_Date + Order_Time and Pickup_Time
# We'll attempt to create proper datetimes by combining Order_Date (if exists) with time strings.
df_clean["Delivery_Time_minutes"] = np.nan  # default column

if {"Order_Time", "Pickup_Time"}.issubset(df_clean.columns):
    # If Order_Date exists, combine date + time to produce full datetimes (preferred)
    if "Order_Date" in df_clean.columns:
        # Convert Order_Date to datetime (coerce errors)
        df_clean["Order_Date"] = pd.to_datetime(df_clean["Order_Date"], errors="coerce")
        # Convert time columns to strings then to times (coerce)
        order_time_str = df_clean["Order_Time"].astype(str).str.strip()
        pickup_time_str = df_clean["Pickup_Time"].astype(str).str.strip()

        # Combine: YYYY-MM-DD + ' ' + time
        order_dt = pd.to_datetime(df_clean["Order_Date"].dt.strftime("%Y-%m-%d") + " " + order_time_str,
                                  errors="coerce")
        pickup_dt = pd.to_datetime(df_clean["Order_Date"].dt.strftime("%Y-%m-%d") + " " + pickup_time_str,
                                   errors="coerce")

        # If pickup is earlier than order (maybe crossed midnight), try adding 1 day to pickup
        negative_mask = (pickup_dt < order_dt) & (~order_dt.isna()) & (~pickup_dt.isna())
        if negative_mask.any():
            pickup_dt.loc[negative_mask] = pickup_dt.loc[negative_mask] + pd.Timedelta(days=1)

        # Calculate minutes
        df_clean.loc[:, "Delivery_Time_minutes"] = (pickup_dt - order_dt).dt.total_seconds() / 60
        n_calculated = int(df_clean["Delivery_Time_minutes"].notna().sum())
        print(f"Calculated Delivery_Time_minutes for {n_calculated} rows using Order_Date + times")
    else:
        # No Order_Date: try parsing times as datetimes (may assume same day) and compute difference
        order_dt = pd.to_datetime(df_clean["Order_Time"], errors="coerce")
        pickup_dt = pd.to_datetime(df_clean["Pickup_Time"], errors="coerce")
        negative_mask = (pickup_dt < order_dt) & (~order_dt.isna()) & (~pickup_dt.isna())
        if negative_mask.any():
            pickup_dt.loc[negative_mask] = pickup_dt.loc[negative_mask] + pd.Timedelta(days=1)
        df_clean.loc[:, "Delivery_Time_minutes"] = (pickup_dt - order_dt).dt.total_seconds() / 60
        n_calculated = int(df_clean["Delivery_Time_minutes"].notna().sum())
        print(f"Calculated Delivery_Time_minutes for {n_calculated} rows using time-only parsing")
else:
    print("Order_Time or Pickup_Time missing -> Delivery_Time_minutes cannot be computed")

# Optional: drop invalid delivery times (negative or extremely large) or mark them NaN
if "Delivery_Time_minutes" in df_clean.columns:
    bad_time_mask = (df_clean["Delivery_Time_minutes"] < 0) | (df_clean["Delivery_Time_minutes"] > 60*24)  # > 24 hours suspicious
    n_bad_time = int(bad_time_mask.sum())
    if n_bad_time > 0:
        df_clean.loc[bad_time_mask, "Delivery_Time_minutes"] = np.nan
        print(f"Marked {n_bad_time} Delivery_Time_minutes as NaN because negative or >24h")

# STEP 11: Calculate Delivery_Distance_km (Haversine). Safe: ensure coords exist and numeric
def haversine_series(lat1, lon1, lat2, lon2):
    # inputs are pandas Series (numeric)
    R = 6371.0
    lat1_r = np.radians(lat1)
    lon1_r = np.radians(lon1)
    lat2_r = np.radians(lat2)
    lon2_r = np.radians(lon2)
    dlat = lat2_r - lat1_r
    dlon = lon2_r - lon1_r
    a = np.sin(dlat/2.0)**2 + np.cos(lat1_r) * np.cos(lat2_r) * np.sin(dlon/2.0)**2
    c = 2 * np.arcsin(np.sqrt(a.clip(0,1)))   # clip for numerical safety
    return R * c

if set(coords).issubset(df_clean.columns):
    df_clean["Delivery_Distance_km"] = haversine_series(
        df_clean["Store_Latitude"], df_clean["Store_Longitude"],
        df_clean["Drop_Latitude"], df_clean["Drop_Longitude"]
    )
    print("Added Delivery_Distance_km column (in kilometers)")
else:
    print("One or more coordinate columns missing -> Delivery_Distance_km not created")

#Step 12:Caculate speed
valid_mask = df_clean["Delivery_Time_minutes"] > 0

df_clean.loc[valid_mask, "Speed_kmph"] = df_clean.loc[valid_mask, "Delivery_Distance_km"] / (df_clean.loc[valid_mask, "Delivery_Time_minutes"] / 60)

print(df_clean[["Delivery_Distance_km", "Delivery_Time_minutes", "Speed_kmph"]].head())

# Step 13: Segmentation for Agent_Age
def age_segment(age):
    if age < 25:
        return "Young"
    elif 25 <= age <= 40:
        return "Adult"
    else:
        return "Senior"

df_clean["Age_Segment"] = df_clean["Agent_Age"].apply(age_segment)

# Segmentation for Order_Rating
def rating_segment(rating):
    if rating < 3.5:
        return "Low"
    elif 3.5 <= rating <= 4.5:
        return "Medium"
    else:
        return "High"

df_clean["Order_Segment"] = df_clean["Order_Rating"].apply(rating_segment)

print(df_clean[["Agent_Age", "Age_Segment", "Order_Rating", "Order_Segment"]].head())

# STEP 14: Final save
df_clean.to_csv(output_path, index=False)
print(f" Cleaned dataset saved as: {output_path}")

print("Table Columns: ")
print(df_clean.columns.tolist())

from google.colab import files
files.download("/content/amazon_delivery_cleaned.csv")